# This should be run from parent folder, to give full project context
FROM golang:1.10.3 as builder
WORKDIR /go/src/github.com/smartfog/fogflow/
COPY . .
WORKDIR /go/src/github.com/smartfog/fogflow/discovery
RUN go get
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -installsuffix cgo  -o discovery

FROM alpine:3.7
COPY --from=builder /go/src/github.com/smartfog/fogflow/discovery/discovery ./
#ADD config.json /
CMD ["/discovery"]
